array_width = 50
attr_fn_like_width = 50
chain_width = 50
disable_all_formatting = false
edition = "2021"
fn_params_layout = "Vertical"
fn_call_width = 50
force_explicit_abi = true
hard_tabs = false
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = true
max_width = 99
merge_derives = false
newline_style = "Auto"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
single_line_if_else_max_width = 40
single_line_let_else_max_width = 30
struct_lit_width = 0
struct_variant_width = 0
tab_spaces = 4
use_field_init_shorthand = false
use_small_heuristics = "Default"
